DROP TABLE tasks IF EXISTS;

CREATE TABLE tasks (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  title          VARCHAR(256) NOT NULL, 
  description    VARCHAR(1024), 
  due_date       DATE, 
  status         VARCHAR(10), 
  creation_date  DATE NOT NULL
);
CREATE INDEX tasks_due_date ON tasks (due_date);